version: '3.8'

services:
  post-linkedin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-linkedin-app
    ports:
      - "3080:3080"
    restart: unless-stopped
    volumes:
      - /volume1/docker/postlinkedin/proposals:/usr/src/app/proposals
      - /volume1/docker/postlinkedin/sources.json:/usr/src/app/sources.json
